### ISSUE TITLE
pysam installation error on MacOS

### ISSUE THREAD

**Issue by IsleZhu** [pritykinlab/guidescanpy#10]
`pip install pysam` failed in MacOS. And The error still occured after I installed `xz` with Homebrew. It can be solved by installing `pysam` manually.

      Collecting pysam
      Using cached pysam-0.21.0.tar.gz (4.1 MB)
      Installing build dependencies ... done
      Getting requirements to build wheel ... error
      error: subprocess-exited-with-error
      
      × Getting requirements to build wheel did not run successfully.
      │ exit code: 1
      ╰─> [170 lines of output]
          ......
          
          checking for lzma_easy_buffer_encode in -llzma... no
          configure: error: liblzma development files not found
          
          The CRAM format may use LZMA2 compression, which is implemented in HTSlib
          by using compression routines from liblzma <http://tukaani.org/xz/>.
          
          Building HTSlib requires liblzma development files to be installed on the
          build machine; you may need to ensure a package such as liblzma-dev (on Debian
          or Ubuntu Linux), xz-devel (on RPM-based Linux distributions or Cygwin), or
          xz (via Homebrew on macOS) is installed; or build XZ Utils from source.
          
          Either configure with --disable-lzma (which will make some CRAM files
          produced elsewhere unreadable) or resolve this error to build HTSlib.
          checking for gcc... clang
          ......
          
          checking for lzma_easy_buffer_encode in -llzma... no
          configure: error: liblzma development files not found
          
          The CRAM format may use LZMA2 compression, which is implemented in HTSlib
          by using compression routines from liblzma <http://tukaani.org/xz/>.
          
          Building HTSlib requires liblzma development files to be installed on the
          build machine; you may need to ensure a package such as liblzma-dev (on Debian
          or Ubuntu Linux), xz-devel (on RPM-based Linux distributions or Cygwin), or
          xz (via Homebrew on macOS) is installed; or build XZ Utils from source.
          
          Either configure with --disable-lzma (which will make some CRAM files
          produced elsewhere unreadable) or resolve this error to build HTSlib.
          Makefile:137: htscodecs.mk: No such file or directory
          config.mk:2: *** Resolve configure error first.  Stop.
          # pysam: htslib configure options: None
          Traceback (most recent call last):
            File "my-path-to/guidescanpy/.env/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
              main()
            File "my-path-to/guidescanpy/.env/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
              json_out['return_val'] = hook(**hook_input['kwargs'])
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            File "my-path-to/guidescanpy/.env/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 118, in get_requires_for_build_wheel
              return hook(config_settings)
                     ^^^^^^^^^^^^^^^^^^^^^
            File "/private/var/folders/5d/5g0416bx01sdbyxq_zkscq180000gp/T/pip-build-env-s5ipgcpl/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
              return self._get_build_requires(config_settings, requirements=['wheel'])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            File "/private/var/folders/5d/5g0416bx01sdbyxq_zkscq180000gp/T/pip-build-env-s5ipgcpl/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
              self.run_setup()
            File "/private/var/folders/5d/5g0416bx01sdbyxq_zkscq180000gp/T/pip-build-env-s5ipgcpl/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 488, in run_setup
              self).run_setup(setup_script=setup_script)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            File "/private/var/folders/5d/5g0416bx01sdbyxq_zkscq180000gp/T/pip-build-env-s5ipgcpl/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in run_setup
              exec(code, locals())
            File "<string>", line 383, in <module>
            File "<string>", line 79, in run_make_print_config
            File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
              return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
              raise CalledProcessError(retcode, process.args,
          subprocess.CalledProcessError: Command '['make', '-s', 'print-config']' returned non-zero exit status 2.
          [end of output]
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: subprocess-exited-with-error
    
    × Getting requirements to build wheel did not run successfully.
    │ exit code: 1
    ╰─> See above for output.
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
 

**Note:** This issue is occurring on MacOS 13.2 with Python 3.11.

**Comment by vineetbansal** [comment]
The underlying issue seems to be that `pysam` has not yet released binary wheels for Python 3.11 for Mac OS. If we look at this list:
https://pypi.org/project/pysam/#files

We see an entry for `pysam-0.21.0-cp310-cp310-macosx_10_9_x86_64.whl` but not a corresponding entry for cp311.

While it's possible to use `brew`/`xcode` etc. under the hood to have `pip` compile and install `pysam` for python 3.11, it's not worth spending time on this. (the `pysam` maintainers need to do this, not us). So it's reasonable for us to say that `guidescanpy` only works on 3.10 for right now, and it will hopefully work in 3.11 in a while once `pysam` catches up.

Note that this doesn't mean that we should tweak our `pyproject.toml` and put in a [requires-python](https://packaging.python.org/en/latest/specifications/declaring-project-metadata/#requires-python) field. If a developer wants to go through the manual process of `pysam` compilation, that's fine.

You will want to try creating an environment in python 3.10 and proceed from there. On a Mac, you can use either anaconda (I'd recommend [miniconda](https://docs.conda.io/en/latest/miniconda.html) instead of the full `anaconda`. Specify the python version when creating the environment:
```
conda create --name guidescanpy python=3.10
```
or [pyenv](https://github.com/pyenv/pyenv), which allows you to switch between python versions easily.

`pyenv` is a better long term solution, but takes a little while to install and getting used to, so I would recommend miniconda for now, since it is an easier starting point for development.

If `pysam` is not installable on 3.10 either, then we have a problem and we can proceed with a different solution.

**Comment by IsleZhu** [comment]
Python 3.10 worked.
